# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/greenfield
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=8090

# JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Jackson
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false

# Thymeleaf
spring.thymeleaf.cache=false