CREATE TABLE IF NOT EXISTS avis_produit (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_client INTEGER NOT NULL,
    id_produit INTEGER NOT NULL,
    nom_client VARCHAR(150) NOT NULL,
    note INTEGER NOT NULL,
    commentaire TEXT,
    date_creation TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_avis_client FOREIGN KEY (id_client) REFERENCES client (id),
    CONSTRAINT fk_avis_produit FOREIGN KEY (id_produit) REFERENCES produit (id)
);